  export enum Countries {
    ARGENTINA = 'Argentina',
    BRASIL = 'Brasil',
    CHILE = 'Chile',
    PARAGUAY = 'Paraguay',
    URUGUAY = 'Uruguay',
    VENEZUELA = 'Venezuela',
    BOLIVIA = 'Bolivia',
    PERU = 'Perú',
    COLOMBIA = 'Colombia',
    ECUADOR = 'Ecuador',
    ESPAÑA = 'España',
    ITALIA = 'Italia',
    EEUU = 'Estados Unidos',
    MEXICO = 'México',
  }