export enum Provinces {
    BUENOS_AIRES = 'Buenos Aires',
    CABA = 'CABA',
    CATAMARCA = 'Catamarca',
    CHACO = 'Chaco',
    CHUBUT = 'Chubut',
    CORDOBA = 'Cordoba',
    CORRIENTES = 'Corrientes',
    ENTRE_RIOS = 'Entre Rios',
    FORMOSA = 'Formosa',
    JUJUY = 'Jujuy',
    LA_PAMPA = 'La Pampa',
    LA_RIOJA = 'La Rioja',
    MENDOZA = 'Mendoza',
    MISIONES = 'Misiones',
    NEUQUEN = 'Neuquen',
    RIO_NEGRO = 'Rio Negro',
    SALTA = 'Salta',
    SAN_JUAN = 'San Juan',
    SAN_LUIS = 'San Luis',
    SANTA_CRUZ = 'Santa Cruz',
    SANTA_FE = 'Santa Fe',
    SANTIAGO_DEL_ESTERO = 'Santiago del Estero',
    TIERRA_DEL_FUEGO = 'Tierra del Fuego',
    TUCUMAN = 'Tucuman',
    OTHER = 'Otra',
  }
  